CMake: Require Qt6::PrintSupport
https://invent.kde.org/system/khelpcenter/-/blob/master/printdoc.h#L11 require `<QPrinter>` ,but CMakeLists.txt without it.

so when i try update khelpcenter to 24.05.1 on guix, i get this error.

```
In file included from /tmp/guix-build-khelpcenter-24.05.1.drv-0/khelpcenter-24.05.1/mainwindow.cpp:20:
/tmp/guix-build-khelpcenter-24.05.1.drv-0/khelpcenter-24.05.1/printdoc.h:11:10: fatal error: QPrinter: No such file or directory
   11 | #include <QPrinter>
      |          ^~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/khelpcenter.dir/build.make:295: CMakeFiles/khelpcenter.dir/mainwindow.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 90%] Linking CXX executable ../bin/khc_xapiansearch
```

and see https://doc.qt.io/qt-6/qprinter.html